services:
  app:
    image: ismailgunayy/ci-cd-test:latest
    ports:
      - "8080:8080"
    container_name: ci-cd-test

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
