name: Release Node.js

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build an push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
